package com.jimi.su.server.model;

import com.jimi.su.server.model.base.BaseBranchtype;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Branchtype extends BaseBranchtype<Branchtype> {
	public static final Branchtype dao = new Branchtype().dao();
}
