package com.jimi.su.server.model;

import com.jimi.su.server.model.base.BaseBranch;


/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Branch extends BaseBranch<Branch> {

	public static final Branch dao = new Branch().dao();
}
