package com.jimi.su.server.model;

import com.jimi.su.server.model.base.BaseCommand;


/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Command extends BaseCommand<Command> {

	public static final Command dao = new Command().dao();
}
