package com.jimi.su.server.model;

import com.jimi.su.server.model.base.BaseDefCommand;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DefCommand extends BaseDefCommand<DefCommand> {
	public static final DefCommand dao = new DefCommand().dao();
}
