package com.jimi.su.server.model;

import com.jimi.su.server.model.base.BaseDevice;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Device extends BaseDevice<Device> {
	public static final Device dao = new Device().dao();
}
