package com.jimi.su.server.model;

import com.jimi.su.server.model.base.BaseDomestic;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Domestic extends BaseDomestic<Domestic> {
	public static final Domestic dao = new Domestic().dao();
}
