package com.jimi.su.server.model;

import com.jimi.su.server.model.base.BaseFile;


/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class File extends BaseFile<File> {

	public static final File dao = new File().dao();
}
