package com.jimi.su.server.model;

import com.jimi.su.server.model.base.BaseForeigntrade;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Foreigntrade extends BaseForeigntrade<Foreigntrade> {
	public static final Foreigntrade dao = new Foreigntrade().dao();
}
