package com.jimi.su.server.model;

import com.jimi.su.server.model.base.BaseGsensor;


/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Gsensor extends BaseGsensor<Gsensor> {

	public static final Gsensor dao = new Gsensor().dao();
}
