package com.jimi.su.server.model;

import com.jimi.su.server.model.base.BaseHardware;


/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Hardware extends BaseHardware<Hardware> {

	public static final Hardware dao = new Hardware().dao();
}
