package com.jimi.su.server.model;

import com.jimi.su.server.model.base.BaseMail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Mail extends BaseMail<Mail> {
	public static final Mail dao = new Mail().dao();
}
