package com.jimi.su.server.model;

import com.jimi.su.server.model.base.BaseOperationversionbind;


/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Operationversionbind extends BaseOperationversionbind<Operationversionbind> {

	public static final Operationversionbind dao = new Operationversionbind().dao();
}
