package com.jimi.su.server.model;

import com.jimi.su.server.model.base.BaseOperation;


/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Operation extends BaseOperation<Operation> {

	public static final Operation dao = new Operation().dao();
}
