package com.jimi.su.server.model;

import com.jimi.su.server.model.base.BaseOrganization;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Organization extends BaseOrganization<Organization> {
	public static final Organization dao = new Organization().dao();
}
