package com.jimi.su.server.model;

import com.jimi.su.server.model.base.BasePcb;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Pcb extends BasePcb<Pcb> {
	public static final Pcb dao = new Pcb().dao();
}
