package com.jimi.su.server.model;

import com.jimi.su.server.model.base.BasePlatform;


/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Platform extends BasePlatform<Platform> {

	public static final Platform dao = new Platform().dao();
}
