package com.jimi.su.server.model;

import com.jimi.su.server.model.base.BaseProject;


/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Project extends BaseProject<Project> {

	public static final Project dao = new Project().dao();
}
