package com.jimi.su.server.model;

import com.jimi.su.server.model.base.BaseRule;


/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Rule extends BaseRule<Rule> {

	public static final Rule dao = new Rule().dao();
}
