package com.jimi.su.server.model;

import com.jimi.su.server.model.base.BaseType;


/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Type extends BaseType<Type> {

	public static final Type dao = new Type().dao();
}
