package com.jimi.su.server.model;

import com.jimi.su.server.model.base.BaseUser;


/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class User extends BaseUser<User> {

	public static final User dao = new User().dao();
}
