package com.jimi.su.server.model;

import com.jimi.su.server.model.base.BaseVersion;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Version extends BaseVersion<Version> {
	public static final Version dao = new Version().dao();
}
