package com.jimi.su.server.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseOrders<M extends BaseOrders<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setOrderName(java.lang.String orderName) {
		set("orderName", orderName);
		return (M)this;
	}
	
	public java.lang.String getOrderName() {
		return getStr("orderName");
	}

	public M setUser(java.lang.Integer user) {
		set("user", user);
		return (M)this;
	}
	
	public java.lang.Integer getUser() {
		return getInt("user");
	}

	public M setBranch(java.lang.Integer branch) {
		set("branch", branch);
		return (M)this;
	}
	
	public java.lang.Integer getBranch() {
		return getInt("branch");
	}

	public M setScalableNum(java.lang.Integer scalableNum) {
		set("scalableNum", scalableNum);
		return (M)this;
	}
	
	public java.lang.Integer getScalableNum() {
		return getInt("scalableNum");
	}

	public M setUpgradedNum(java.lang.Integer upgradedNum) {
		set("upgradedNum", upgradedNum);
		return (M)this;
	}
	
	public java.lang.Integer getUpgradedNum() {
		return getInt("upgradedNum");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
		return (M)this;
	}
	
	public java.util.Date getCreateTime() {
		return get("createTime");
	}

}
