package com.jimi.su.server.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseFile<M extends BaseFile<M>> extends Model<M> implements IBean {

	public M setID(java.lang.Integer ID) {
		set("ID", ID);
		return (M)this;
	}
	
	public java.lang.Integer getID() {
		return getInt("ID");
	}

	public M setFileName(java.lang.String FileName) {
		set("FileName", FileName);
		return (M)this;
	}
	
	public java.lang.String getFileName() {
		return getStr("FileName");
	}

	public M setBranchID(java.lang.Integer BranchID) {
		set("BranchID", BranchID);
		return (M)this;
	}
	
	public java.lang.Integer getBranchID() {
		return getInt("BranchID");
	}

	public M setPath(java.lang.String Path) {
		set("Path", Path);
		return (M)this;
	}
	
	public java.lang.String getPath() {
		return getStr("Path");
	}

	public M setFileSize(java.lang.Integer FileSize) {
		set("FileSize", FileSize);
		return (M)this;
	}
	
	public java.lang.Integer getFileSize() {
		return getInt("FileSize");
	}

	public M setPackTime(java.util.Date PackTime) {
		set("PackTime", PackTime);
		return (M)this;
	}
	
	public java.util.Date getPackTime() {
		return get("PackTime");
	}

	public M setUpdateLog(java.lang.String UpdateLog) {
		set("UpdateLog", UpdateLog);
		return (M)this;
	}
	
	public java.lang.String getUpdateLog() {
		return getStr("UpdateLog");
	}

	public M setMD5Code(java.lang.String MD5Code) {
		set("MD5Code", MD5Code);
		return (M)this;
	}
	
	public java.lang.String getMD5Code() {
		return getStr("MD5Code");
	}

}
