package com.jimi.su.server.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseDefCommand<M extends BaseDefCommand<M>> extends Model<M> implements IBean {

	public M setID(java.lang.Long ID) {
		set("ID", ID);
		return (M)this;
	}
	
	public java.lang.Long getID() {
		return getLong("ID");
	}

	public M setCommandName(java.lang.String CommandName) {
		set("CommandName", CommandName);
		return (M)this;
	}
	
	public java.lang.String getCommandName() {
		return getStr("CommandName");
	}

	public M setCommand(java.lang.String Command) {
		set("Command", Command);
		return (M)this;
	}
	
	public java.lang.String getCommand() {
		return getStr("Command");
	}

	public M setRecvTitle(java.lang.String RecvTitle) {
		set("RecvTitle", RecvTitle);
		return (M)this;
	}
	
	public java.lang.String getRecvTitle() {
		return getStr("RecvTitle");
	}

	public M setTitleIndex(java.lang.String TitleIndex) {
		set("TitleIndex", TitleIndex);
		return (M)this;
	}
	
	public java.lang.String getTitleIndex() {
		return getStr("TitleIndex");
	}

	public M setLimitLength(java.lang.Long LimitLength) {
		set("LimitLength", LimitLength);
		return (M)this;
	}
	
	public java.lang.Long getLimitLength() {
		return getLong("LimitLength");
	}

	public M setStartRange(java.lang.Integer StartRange) {
		set("StartRange", StartRange);
		return (M)this;
	}
	
	public java.lang.Integer getStartRange() {
		return getInt("StartRange");
	}

	public M setEndRange(java.lang.Integer EndRange) {
		set("EndRange", EndRange);
		return (M)this;
	}
	
	public java.lang.Integer getEndRange() {
		return getInt("EndRange");
	}

	public M setReadORWrite(java.lang.Integer ReadORWrite) {
		set("ReadORWrite", ReadORWrite);
		return (M)this;
	}
	
	public java.lang.Integer getReadORWrite() {
		return getInt("ReadORWrite");
	}

	public M setReWrite(java.lang.Integer ReWrite) {
		set("ReWrite", ReWrite);
		return (M)this;
	}
	
	public java.lang.Integer getReWrite() {
		return getInt("ReWrite");
	}

	public M setProjectID(java.lang.Integer ProjectID) {
		set("ProjectID", ProjectID);
		return (M)this;
	}
	
	public java.lang.Integer getProjectID() {
		return getInt("ProjectID");
	}

	public M setBranchID(java.lang.Integer BranchID) {
		set("BranchID", BranchID);
		return (M)this;
	}
	
	public java.lang.Integer getBranchID() {
		return getInt("BranchID");
	}

}
