package com.jimi.su.server.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseBranch<M extends BaseBranch<M>> extends Model<M> implements IBean {

	public M setID(java.lang.Integer ID) {
		set("ID", ID);
		return (M)this;
	}
	
	public java.lang.Integer getID() {
		return getInt("ID");
	}

	public M setBranchName(java.lang.String BranchName) {
		set("BranchName", BranchName);
		return (M)this;
	}
	
	public java.lang.String getBranchName() {
		return getStr("BranchName");
	}

	public M setDomainName(java.lang.String DomainName) {
		set("DomainName", DomainName);
		return (M)this;
	}
	
	public java.lang.String getDomainName() {
		return getStr("DomainName");
	}

	public M setBranchVersion(java.lang.String BranchVersion) {
		set("BranchVersion", BranchVersion);
		return (M)this;
	}
	
	public java.lang.String getBranchVersion() {
		return getStr("BranchVersion");
	}

	public M setLock(java.lang.String Lock) {
		set("Lock", Lock);
		return (M)this;
	}
	
	public java.lang.String getLock() {
		return getStr("Lock");
	}

	public M setParamVersion(java.lang.String ParamVersion) {
		set("ParamVersion", ParamVersion);
		return (M)this;
	}
	
	public java.lang.String getParamVersion() {
		return getStr("ParamVersion");
	}

	public M setPatch(java.lang.Boolean Patch) {
		set("Patch", Patch);
		return (M)this;
	}
	
	public java.lang.Boolean getPatch() {
		return get("Patch");
	}

	public M setComposite(java.lang.Boolean Composite) {
		set("Composite", Composite);
		return (M)this;
	}
	
	public java.lang.Boolean getComposite() {
		return get("Composite");
	}

	public M setRemarks(java.lang.String Remarks) {
		set("Remarks", Remarks);
		return (M)this;
	}
	
	public java.lang.String getRemarks() {
		return getStr("Remarks");
	}

	public M setPcbID(java.lang.Integer PcbID) {
		set("PcbID", PcbID);
		return (M)this;
	}
	
	public java.lang.Integer getPcbID() {
		return getInt("PcbID");
	}

	public M setHwID(java.lang.Integer HwID) {
		set("HwID", HwID);
		return (M)this;
	}
	
	public java.lang.Integer getHwID() {
		return getInt("HwID");
	}

	public M setGsensorID(java.lang.Integer GsensorID) {
		set("GsensorID", GsensorID);
		return (M)this;
	}
	
	public java.lang.Integer getGsensorID() {
		return getInt("GsensorID");
	}

	public M setBranchTypeID(java.lang.Integer BranchTypeID) {
		set("BranchTypeID", BranchTypeID);
		return (M)this;
	}
	
	public java.lang.Integer getBranchTypeID() {
		return getInt("BranchTypeID");
	}

	public M setPfID(java.lang.Integer PfID) {
		set("PfID", PfID);
		return (M)this;
	}
	
	public java.lang.Integer getPfID() {
		return getInt("PfID");
	}

}
