package com.jimi.su.server.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseMail<M extends BaseMail<M>> extends Model<M> implements IBean {

	public M setID(java.lang.Integer ID) {
		set("ID", ID);
		return (M)this;
	}
	
	public java.lang.Integer getID() {
		return getInt("ID");
	}

	public M setEMailAddress(java.lang.String EMailAddress) {
		set("EMailAddress", EMailAddress);
		return (M)this;
	}
	
	public java.lang.String getEMailAddress() {
		return getStr("EMailAddress");
	}

	public M setUserID(java.lang.Integer UserID) {
		set("UserID", UserID);
		return (M)this;
	}
	
	public java.lang.Integer getUserID() {
		return getInt("UserID");
	}

}
