package com.jimi.su.server.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseDomestic<M extends BaseDomestic<M>> extends Model<M> implements IBean {

	public M setID(java.lang.Integer ID) {
		set("ID", ID);
		return (M)this;
	}
	
	public java.lang.Integer getID() {
		return getInt("ID");
	}

	public M setDomesticName(java.lang.String DomesticName) {
		set("DomesticName", DomesticName);
		return (M)this;
	}
	
	public java.lang.String getDomesticName() {
		return getStr("DomesticName");
	}

}
