package com.jimi.su.server.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseHardware<M extends BaseHardware<M>> extends Model<M> implements IBean {

	public M setID(java.lang.Integer ID) {
		set("ID", ID);
		return (M)this;
	}
	
	public java.lang.Integer getID() {
		return getInt("ID");
	}

	public M setHwVersion(java.lang.String HwVersion) {
		set("HwVersion", HwVersion);
		return (M)this;
	}
	
	public java.lang.String getHwVersion() {
		return getStr("HwVersion");
	}

}
