package com.jimi.su.server.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseBranchtype<M extends BaseBranchtype<M>> extends Model<M> implements IBean {

	public M setID(java.lang.Integer ID) {
		set("ID", ID);
		return (M)this;
	}
	
	public java.lang.Integer getID() {
		return getInt("ID");
	}

	public M setType(java.lang.Boolean Type) {
		set("Type", Type);
		return (M)this;
	}
	
	public java.lang.Boolean getType() {
		return get("Type");
	}

	public M setName(java.lang.String Name) {
		set("Name", Name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("Name");
	}

	public M setProjectID(java.lang.Integer ProjectID) {
		set("ProjectID", ProjectID);
		return (M)this;
	}
	
	public java.lang.Integer getProjectID() {
		return getInt("ProjectID");
	}

	public M setPosition(java.lang.Integer Position) {
		set("Position", Position);
		return (M)this;
	}
	
	public java.lang.Integer getPosition() {
		return getInt("Position");
	}

}
